# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b285982a01539ccb8d800263d2729de8aecd5ff1c0aa6d5620e8a7aa4fafd5e714f1a74bd4cc58288fa6e2eae933931329e7a0762c5ea2fee9040510ff006f

test:
  secret_key_base: e774b5f8cdf3cc811fb2e54b8960b72b03f43f0769921b26edb0116481297897338bfaa1cbd00b91c2031f05c83815fea53a5402aea655b6acf6241218386b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
